# -*- coding: utf-8 -*-
"""Dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISSU_t3PSkmpQ8XFpc8fnqCiIX180yga

struct to dictionary
"""

student = {
    "Name": "Harsh",
    "Roll": 10,
    "Marks": 90.99
}

print("Student Details:")
print(f"Name  : {student['Name']}")
print(f"Roll  : {student['Roll']}")
print(f"Marks : {student['Marks']}")